name: Compile LaTeX
description: "Compile LaTeX"

inputs:
  working-directory:
    description: The Working Directory
    required: false
    default: ${{ github.workspace }}

  input-file:
    description: Name of LaTeX File (with .tex extension)
    required: false
    default: main.tex

  job-name:
    description: Name of Compiled PDF File (without .pdf extension)
    required: false
    default: main

  compiler:
    description: LaTeX Compiler
    required: false
    default: latexmk

  args:
    description: Arguments 
    required: false
    default: -pdflatex -interaction=nonstopmode -file-line-error

  cache:
    description: Caching of Auxiliary Files
    required: false
    default: true

  version:
    description: Enable Version Information
    required: false
    default: true

  upload:
    description: Upload Output PDF to Artifacts
    required: false
    default: true

outputs:
  pdf-name:
    description: Name of PDF of Output
    value: ${{ steps.job-name-creation.outputs.job-name }}

runs:
  using: "composite"

  steps:
    - name: Read File Paths to Cache
      id: cache-paths
      shell: bash
      run: |
        echo "paths<<EOF" >> $GITHUB_OUTPUT
        sed 's|^|${{ inputs.working-directory }}/**/|' ${{ github.action_path }}/cache.file.list >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Cache LaTeX auxiliary files
      if: inputs.cache == 'true'
      uses: actions/cache@v5
      with:
        path: ${{ steps.cache-paths.outputs.paths }}
        key: ${{ runner.os }}-latex-compile-${{ inputs.working-directory }}/${{ inputs.input-file }}

    - name: Retrieve Version Information
      id: retrieve-version
      shell: bash
      run: |
        echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "date=$(git log -1 --format=%cd --date=format:%Y%m%d)" >> $GITHUB_OUTPUT

    - name: Create Version File
      shell: bash
      if: inputs.version == 'true'
      run: |
        echo "" >> version.tex
        echo "\renewcommand{\DATE}{${{ steps.retrieve-version.outputs.sha }}}" >> version.tex
        echo "\renewcommand{\COMMITSHA}{${{ steps.retrieve-version.outputs.date }}}" >> version.tex

    - name: Create Output Filename
      shell: bash
      id: job-name-creation
      run: echo "$job-name={{ inputs.job-name }}-${{ steps.retrieve-version.outputs.sha }}-${{ steps.retrieve-version.outputs.date }}" >> $GITHUB_OUTPUT
      

    - name: Compile LaTeX File
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: ${{ inputs.compiler }} ${{ inputs.args }} -jobname=${{ steps.output.job-name-creation.job-name }} ${{ inputs.input-file }}
    
    - name: Upload PDF file
      uses: actions/upload-artifact@v7
      if: inputs.upload == 'true'
      with:
        archive: false
        path: ${{ inputs.working-directory }}/${{ inputs.job-name }}.pdf